// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/shopspring/decimal"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SyndicateWinDistribution is an object representing the database table.
type SyndicateWinDistribution struct {
	ID                      string          `boiler:"id" boil:"id" json:"id" toml:"id" yaml:"id"`
	DeployingUserPercentage decimal.Decimal `boiler:"deploying_user_percentage" boil:"deploying_user_percentage" json:"deploying_user_percentage" toml:"deploying_user_percentage" yaml:"deploying_user_percentage"`
	AbilityKillPercentage   decimal.Decimal `boiler:"ability_kill_percentage" boil:"ability_kill_percentage" json:"ability_kill_percentage" toml:"ability_kill_percentage" yaml:"ability_kill_percentage"`
	MechOwnerPercentage     decimal.Decimal `boiler:"mech_owner_percentage" boil:"mech_owner_percentage" json:"mech_owner_percentage" toml:"mech_owner_percentage" yaml:"mech_owner_percentage"`
	SyndicateCutPercentage  decimal.Decimal `boiler:"syndicate_cut_percentage" boil:"syndicate_cut_percentage" json:"syndicate_cut_percentage" toml:"syndicate_cut_percentage" yaml:"syndicate_cut_percentage"`
	CreatedAt               time.Time       `boiler:"created_at" boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt               time.Time       `boiler:"updated_at" boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt               null.Time       `boiler:"deleted_at" boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *syndicateWinDistributionR `boiler:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L syndicateWinDistributionL  `boiler:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SyndicateWinDistributionColumns = struct {
	ID                      string
	DeployingUserPercentage string
	AbilityKillPercentage   string
	MechOwnerPercentage     string
	SyndicateCutPercentage  string
	CreatedAt               string
	UpdatedAt               string
	DeletedAt               string
}{
	ID:                      "id",
	DeployingUserPercentage: "deploying_user_percentage",
	AbilityKillPercentage:   "ability_kill_percentage",
	MechOwnerPercentage:     "mech_owner_percentage",
	SyndicateCutPercentage:  "syndicate_cut_percentage",
	CreatedAt:               "created_at",
	UpdatedAt:               "updated_at",
	DeletedAt:               "deleted_at",
}

var SyndicateWinDistributionTableColumns = struct {
	ID                      string
	DeployingUserPercentage string
	AbilityKillPercentage   string
	MechOwnerPercentage     string
	SyndicateCutPercentage  string
	CreatedAt               string
	UpdatedAt               string
	DeletedAt               string
}{
	ID:                      "syndicate_win_distributions.id",
	DeployingUserPercentage: "syndicate_win_distributions.deploying_user_percentage",
	AbilityKillPercentage:   "syndicate_win_distributions.ability_kill_percentage",
	MechOwnerPercentage:     "syndicate_win_distributions.mech_owner_percentage",
	SyndicateCutPercentage:  "syndicate_win_distributions.syndicate_cut_percentage",
	CreatedAt:               "syndicate_win_distributions.created_at",
	UpdatedAt:               "syndicate_win_distributions.updated_at",
	DeletedAt:               "syndicate_win_distributions.deleted_at",
}

// Generated where

var SyndicateWinDistributionWhere = struct {
	ID                      whereHelperstring
	DeployingUserPercentage whereHelperdecimal_Decimal
	AbilityKillPercentage   whereHelperdecimal_Decimal
	MechOwnerPercentage     whereHelperdecimal_Decimal
	SyndicateCutPercentage  whereHelperdecimal_Decimal
	CreatedAt               whereHelpertime_Time
	UpdatedAt               whereHelpertime_Time
	DeletedAt               whereHelpernull_Time
}{
	ID:                      whereHelperstring{field: "\"syndicate_win_distributions\".\"id\""},
	DeployingUserPercentage: whereHelperdecimal_Decimal{field: "\"syndicate_win_distributions\".\"deploying_user_percentage\""},
	AbilityKillPercentage:   whereHelperdecimal_Decimal{field: "\"syndicate_win_distributions\".\"ability_kill_percentage\""},
	MechOwnerPercentage:     whereHelperdecimal_Decimal{field: "\"syndicate_win_distributions\".\"mech_owner_percentage\""},
	SyndicateCutPercentage:  whereHelperdecimal_Decimal{field: "\"syndicate_win_distributions\".\"syndicate_cut_percentage\""},
	CreatedAt:               whereHelpertime_Time{field: "\"syndicate_win_distributions\".\"created_at\""},
	UpdatedAt:               whereHelpertime_Time{field: "\"syndicate_win_distributions\".\"updated_at\""},
	DeletedAt:               whereHelpernull_Time{field: "\"syndicate_win_distributions\".\"deleted_at\""},
}

// SyndicateWinDistributionRels is where relationship names are stored.
var SyndicateWinDistributionRels = struct {
	IDSyndicate string
}{
	IDSyndicate: "IDSyndicate",
}

// syndicateWinDistributionR is where relationships are stored.
type syndicateWinDistributionR struct {
	IDSyndicate *Syndicate `boiler:"IDSyndicate" boil:"IDSyndicate" json:"IDSyndicate" toml:"IDSyndicate" yaml:"IDSyndicate"`
}

// NewStruct creates a new relationship struct
func (*syndicateWinDistributionR) NewStruct() *syndicateWinDistributionR {
	return &syndicateWinDistributionR{}
}

// syndicateWinDistributionL is where Load methods for each relationship are stored.
type syndicateWinDistributionL struct{}

var (
	syndicateWinDistributionAllColumns            = []string{"id", "deploying_user_percentage", "ability_kill_percentage", "mech_owner_percentage", "syndicate_cut_percentage", "created_at", "updated_at", "deleted_at"}
	syndicateWinDistributionColumnsWithoutDefault = []string{"id"}
	syndicateWinDistributionColumnsWithDefault    = []string{"deploying_user_percentage", "ability_kill_percentage", "mech_owner_percentage", "syndicate_cut_percentage", "created_at", "updated_at", "deleted_at"}
	syndicateWinDistributionPrimaryKeyColumns     = []string{"id"}
	syndicateWinDistributionGeneratedColumns      = []string{}
)

type (
	// SyndicateWinDistributionSlice is an alias for a slice of pointers to SyndicateWinDistribution.
	// This should almost always be used instead of []SyndicateWinDistribution.
	SyndicateWinDistributionSlice []*SyndicateWinDistribution
	// SyndicateWinDistributionHook is the signature for custom SyndicateWinDistribution hook methods
	SyndicateWinDistributionHook func(boil.Executor, *SyndicateWinDistribution) error

	syndicateWinDistributionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	syndicateWinDistributionType                 = reflect.TypeOf(&SyndicateWinDistribution{})
	syndicateWinDistributionMapping              = queries.MakeStructMapping(syndicateWinDistributionType)
	syndicateWinDistributionPrimaryKeyMapping, _ = queries.BindMapping(syndicateWinDistributionType, syndicateWinDistributionMapping, syndicateWinDistributionPrimaryKeyColumns)
	syndicateWinDistributionInsertCacheMut       sync.RWMutex
	syndicateWinDistributionInsertCache          = make(map[string]insertCache)
	syndicateWinDistributionUpdateCacheMut       sync.RWMutex
	syndicateWinDistributionUpdateCache          = make(map[string]updateCache)
	syndicateWinDistributionUpsertCacheMut       sync.RWMutex
	syndicateWinDistributionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var syndicateWinDistributionAfterSelectHooks []SyndicateWinDistributionHook

var syndicateWinDistributionBeforeInsertHooks []SyndicateWinDistributionHook
var syndicateWinDistributionAfterInsertHooks []SyndicateWinDistributionHook

var syndicateWinDistributionBeforeUpdateHooks []SyndicateWinDistributionHook
var syndicateWinDistributionAfterUpdateHooks []SyndicateWinDistributionHook

var syndicateWinDistributionBeforeDeleteHooks []SyndicateWinDistributionHook
var syndicateWinDistributionAfterDeleteHooks []SyndicateWinDistributionHook

var syndicateWinDistributionBeforeUpsertHooks []SyndicateWinDistributionHook
var syndicateWinDistributionAfterUpsertHooks []SyndicateWinDistributionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SyndicateWinDistribution) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SyndicateWinDistribution) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SyndicateWinDistribution) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SyndicateWinDistribution) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SyndicateWinDistribution) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SyndicateWinDistribution) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SyndicateWinDistribution) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SyndicateWinDistribution) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SyndicateWinDistribution) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range syndicateWinDistributionAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSyndicateWinDistributionHook registers your hook function for all future operations.
func AddSyndicateWinDistributionHook(hookPoint boil.HookPoint, syndicateWinDistributionHook SyndicateWinDistributionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		syndicateWinDistributionAfterSelectHooks = append(syndicateWinDistributionAfterSelectHooks, syndicateWinDistributionHook)
	case boil.BeforeInsertHook:
		syndicateWinDistributionBeforeInsertHooks = append(syndicateWinDistributionBeforeInsertHooks, syndicateWinDistributionHook)
	case boil.AfterInsertHook:
		syndicateWinDistributionAfterInsertHooks = append(syndicateWinDistributionAfterInsertHooks, syndicateWinDistributionHook)
	case boil.BeforeUpdateHook:
		syndicateWinDistributionBeforeUpdateHooks = append(syndicateWinDistributionBeforeUpdateHooks, syndicateWinDistributionHook)
	case boil.AfterUpdateHook:
		syndicateWinDistributionAfterUpdateHooks = append(syndicateWinDistributionAfterUpdateHooks, syndicateWinDistributionHook)
	case boil.BeforeDeleteHook:
		syndicateWinDistributionBeforeDeleteHooks = append(syndicateWinDistributionBeforeDeleteHooks, syndicateWinDistributionHook)
	case boil.AfterDeleteHook:
		syndicateWinDistributionAfterDeleteHooks = append(syndicateWinDistributionAfterDeleteHooks, syndicateWinDistributionHook)
	case boil.BeforeUpsertHook:
		syndicateWinDistributionBeforeUpsertHooks = append(syndicateWinDistributionBeforeUpsertHooks, syndicateWinDistributionHook)
	case boil.AfterUpsertHook:
		syndicateWinDistributionAfterUpsertHooks = append(syndicateWinDistributionAfterUpsertHooks, syndicateWinDistributionHook)
	}
}

// One returns a single syndicateWinDistribution record from the query.
func (q syndicateWinDistributionQuery) One(exec boil.Executor) (*SyndicateWinDistribution, error) {
	o := &SyndicateWinDistribution{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for syndicate_win_distributions")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SyndicateWinDistribution records from the query.
func (q syndicateWinDistributionQuery) All(exec boil.Executor) (SyndicateWinDistributionSlice, error) {
	var o []*SyndicateWinDistribution

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to SyndicateWinDistribution slice")
	}

	if len(syndicateWinDistributionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SyndicateWinDistribution records in the query.
func (q syndicateWinDistributionQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count syndicate_win_distributions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q syndicateWinDistributionQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if syndicate_win_distributions exists")
	}

	return count > 0, nil
}

// IDSyndicate pointed to by the foreign key.
func (o *SyndicateWinDistribution) IDSyndicate(mods ...qm.QueryMod) syndicateQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ID),
		qmhelper.WhereIsNull("deleted_at"),
	}

	queryMods = append(queryMods, mods...)

	query := Syndicates(queryMods...)
	queries.SetFrom(query.Query, "\"syndicates\"")

	return query
}

// LoadIDSyndicate allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (syndicateWinDistributionL) LoadIDSyndicate(e boil.Executor, singular bool, maybeSyndicateWinDistribution interface{}, mods queries.Applicator) error {
	var slice []*SyndicateWinDistribution
	var object *SyndicateWinDistribution

	if singular {
		object = maybeSyndicateWinDistribution.(*SyndicateWinDistribution)
	} else {
		slice = *maybeSyndicateWinDistribution.(*[]*SyndicateWinDistribution)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &syndicateWinDistributionR{}
		}
		args = append(args, object.ID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &syndicateWinDistributionR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`syndicates`),
		qm.WhereIn(`syndicates.id in ?`, args...),
		qmhelper.WhereIsNull(`syndicates.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Syndicate")
	}

	var resultSlice []*Syndicate
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Syndicate")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for syndicates")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for syndicates")
	}

	if len(syndicateWinDistributionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.IDSyndicate = foreign
		if foreign.R == nil {
			foreign.R = &syndicateR{}
		}
		foreign.R.IDSyndicateWinDistribution = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ID == foreign.ID {
				local.R.IDSyndicate = foreign
				if foreign.R == nil {
					foreign.R = &syndicateR{}
				}
				foreign.R.IDSyndicateWinDistribution = local
				break
			}
		}
	}

	return nil
}

// SetIDSyndicate of the syndicateWinDistribution to the related item.
// Sets o.R.IDSyndicate to related.
// Adds o to related.R.IDSyndicateWinDistribution.
func (o *SyndicateWinDistribution) SetIDSyndicate(exec boil.Executor, insert bool, related *Syndicate) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"syndicate_win_distributions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"id"}),
		strmangle.WhereClause("\"", "\"", 2, syndicateWinDistributionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ID = related.ID
	if o.R == nil {
		o.R = &syndicateWinDistributionR{
			IDSyndicate: related,
		}
	} else {
		o.R.IDSyndicate = related
	}

	if related.R == nil {
		related.R = &syndicateR{
			IDSyndicateWinDistribution: o,
		}
	} else {
		related.R.IDSyndicateWinDistribution = o
	}

	return nil
}

// SyndicateWinDistributions retrieves all the records using an executor.
func SyndicateWinDistributions(mods ...qm.QueryMod) syndicateWinDistributionQuery {
	mods = append(mods, qm.From("\"syndicate_win_distributions\""), qmhelper.WhereIsNull("\"syndicate_win_distributions\".\"deleted_at\""))
	return syndicateWinDistributionQuery{NewQuery(mods...)}
}

// FindSyndicateWinDistribution retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSyndicateWinDistribution(exec boil.Executor, iD string, selectCols ...string) (*SyndicateWinDistribution, error) {
	syndicateWinDistributionObj := &SyndicateWinDistribution{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"syndicate_win_distributions\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, syndicateWinDistributionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from syndicate_win_distributions")
	}

	if err = syndicateWinDistributionObj.doAfterSelectHooks(exec); err != nil {
		return syndicateWinDistributionObj, err
	}

	return syndicateWinDistributionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SyndicateWinDistribution) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no syndicate_win_distributions provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(syndicateWinDistributionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	syndicateWinDistributionInsertCacheMut.RLock()
	cache, cached := syndicateWinDistributionInsertCache[key]
	syndicateWinDistributionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			syndicateWinDistributionAllColumns,
			syndicateWinDistributionColumnsWithDefault,
			syndicateWinDistributionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(syndicateWinDistributionType, syndicateWinDistributionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(syndicateWinDistributionType, syndicateWinDistributionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"syndicate_win_distributions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"syndicate_win_distributions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into syndicate_win_distributions")
	}

	if !cached {
		syndicateWinDistributionInsertCacheMut.Lock()
		syndicateWinDistributionInsertCache[key] = cache
		syndicateWinDistributionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the SyndicateWinDistribution.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SyndicateWinDistribution) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	syndicateWinDistributionUpdateCacheMut.RLock()
	cache, cached := syndicateWinDistributionUpdateCache[key]
	syndicateWinDistributionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			syndicateWinDistributionAllColumns,
			syndicateWinDistributionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update syndicate_win_distributions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"syndicate_win_distributions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, syndicateWinDistributionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(syndicateWinDistributionType, syndicateWinDistributionMapping, append(wl, syndicateWinDistributionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update syndicate_win_distributions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for syndicate_win_distributions")
	}

	if !cached {
		syndicateWinDistributionUpdateCacheMut.Lock()
		syndicateWinDistributionUpdateCache[key] = cache
		syndicateWinDistributionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q syndicateWinDistributionQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for syndicate_win_distributions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for syndicate_win_distributions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SyndicateWinDistributionSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syndicateWinDistributionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"syndicate_win_distributions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, syndicateWinDistributionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in syndicateWinDistribution slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all syndicateWinDistribution")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SyndicateWinDistribution) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no syndicate_win_distributions provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(syndicateWinDistributionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	syndicateWinDistributionUpsertCacheMut.RLock()
	cache, cached := syndicateWinDistributionUpsertCache[key]
	syndicateWinDistributionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			syndicateWinDistributionAllColumns,
			syndicateWinDistributionColumnsWithDefault,
			syndicateWinDistributionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			syndicateWinDistributionAllColumns,
			syndicateWinDistributionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("boiler: unable to upsert syndicate_win_distributions, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(syndicateWinDistributionPrimaryKeyColumns))
			copy(conflict, syndicateWinDistributionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"syndicate_win_distributions\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(syndicateWinDistributionType, syndicateWinDistributionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(syndicateWinDistributionType, syndicateWinDistributionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert syndicate_win_distributions")
	}

	if !cached {
		syndicateWinDistributionUpsertCacheMut.Lock()
		syndicateWinDistributionUpsertCache[key] = cache
		syndicateWinDistributionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single SyndicateWinDistribution record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SyndicateWinDistribution) Delete(exec boil.Executor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no SyndicateWinDistribution provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), syndicateWinDistributionPrimaryKeyMapping)
		sql = "DELETE FROM \"syndicate_win_distributions\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"syndicate_win_distributions\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(syndicateWinDistributionType, syndicateWinDistributionMapping, append(wl, syndicateWinDistributionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from syndicate_win_distributions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for syndicate_win_distributions")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q syndicateWinDistributionQuery) DeleteAll(exec boil.Executor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no syndicateWinDistributionQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from syndicate_win_distributions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for syndicate_win_distributions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SyndicateWinDistributionSlice) DeleteAll(exec boil.Executor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(syndicateWinDistributionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syndicateWinDistributionPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"syndicate_win_distributions\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, syndicateWinDistributionPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syndicateWinDistributionPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"syndicate_win_distributions\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, syndicateWinDistributionPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from syndicateWinDistribution slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for syndicate_win_distributions")
	}

	if len(syndicateWinDistributionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SyndicateWinDistribution) Reload(exec boil.Executor) error {
	ret, err := FindSyndicateWinDistribution(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SyndicateWinDistributionSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SyndicateWinDistributionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syndicateWinDistributionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"syndicate_win_distributions\".* FROM \"syndicate_win_distributions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, syndicateWinDistributionPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in SyndicateWinDistributionSlice")
	}

	*o = slice

	return nil
}

// SyndicateWinDistributionExists checks if the SyndicateWinDistribution row exists.
func SyndicateWinDistributionExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"syndicate_win_distributions\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if syndicate_win_distributions exists")
	}

	return exists, nil
}
