DELETE FROM kv WHERE key NOT IN ('sale_ability_floor_price',
'sale_ability_reduction_percentage',
'sale_ability_inflation_percentage',
'sale_ability_time_between_refresh_seconds',
'sale_ability_purchase_limit',
'sale_ability_claim_limit',
'sale_ability_price_ticker_interval_seconds',
'sale_ability_limit',
'player_ability_ability_incognito_duration_seconds',
'marketplace_listing_fee',
'marketplace_listing_buyout_fee',
'marketplace_listing_auction_reserve_fee',
'marketplace_sale_cut_percentage_fee',
'battle_ability_bribe_duration',
'battle_ability_location_select_duration',
'advance_battle_ability_show_up_until_seconds',
'advance_battle_ability_label',
'punish_vote_cooldown_hour',
'last_transfer_event_id',
'instant_pass_required_amount',
'system_ban_judging_countdown_seconds',
'system_ban_team_kill_default_reason',
'system_ban_team_kill_ban_base_duration_hours',
'system_ban_team_kill_ban_duration_multiplier',
'system_ban_team_kill_permanent_ban_bottom_line_hours',
'mech_ability_cool_down_seconds',
'mech_repair_default_duration_minutes',
'mech_fast_repair_duration_minutes',
'mech_standard_repair_fee',
'mech_fast_repair_fee',
'decentralised_autonomous_syndicate_tax',
'corporation_syndicate_tax');

UPDATE  game_abilities SET level = 'PLAYER' WHERE  game_client_ability_id = 5 or game_client_ability_id = 2;

INSERT INTO game_abilities (game_client_ability_id, faction_id, battle_ability_id, label, colour, image_url, description, text_colour, level, location_select_type)
VALUES  (2, '7c6dde21-b067-46cf-9e56-155c88a520e2', null, 'REPAIR', '#23AE3C', 'https://afiles.ninja-cdn.com/supremacy-stream-site/assets/img/ability-repair.jpg', 'Support your Syndicate with a well-timed repair.', '#FFFFFF', 'PLAYER', 'LOCATION_SELECT'),
        (2, '98bf7bb3-1a7c-4f21-8843-458d62884060', null, 'REPAIR', '#23AE3C', 'https://afiles.ninja-cdn.com/supremacy-stream-site/assets/img/ability-repair.jpg', 'Support your Syndicate with a well-timed repair.', '#FFFFFF', 'PLAYER', 'LOCATION_SELECT'),
        (2, '880db344-e405-428d-84e5-6ebebab1fe6d', null, 'REPAIR', '#23AE3C', 'https://afiles.ninja-cdn.com/supremacy-stream-site/assets/img/ability-repair.jpg', 'Support your Syndicate with a well-timed repair.', '#FFFFFF', 'PLAYER', 'LOCATION_SELECT');
