DROP TYPE IF EXISTS ABILITY_LEVEL;
CREATE TYPE ABILITY_LEVEL AS ENUM ('MECH','FACTION','PLAYER');
ALTER TABLE game_abilities ADD COLUMN level ABILITY_LEVEL NOT NULL DEFAULT 'FACTION';
UPDATE game_abilities SET level = 'MECH' WHERE label = 'FIREWORKS' or label = 'OVERCHARGE';