-- BEGIN;
-- ALTER TYPE collection ADD VALUE 'supremacy-achievements';
-- COMMIT;

CREATE TABLE blueprint_keycards
(
    id               UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    label            TEXT             NOT NULL,
    description      TEXT             NOT NULL,
    collection       collection       NOT NULL,
    keycard_token_id INT UNIQUE       NOT NULL,
    image_url        TEXT             NOT NULL,
    animation_url    TEXT             NULL,
    keycard_group    TEXT             NOT NULL,
    syndicate        TEXT             NULL,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

INSERT INTO blueprint_keycards (id, label, description, collection, keycard_token_id, image_url, animation_url,
                                keycard_group, syndicate)
VALUES ('c60c2b6a-72e5-4d6e-b273-0e3f1b5441a4', 'Early Contributor',
        'You were one of the very first people to pledge allegiance in Supremacy. Your belief carried us forward.',
        'supremacy-achievements', 0, 'https://achievements.supremacy.game/assets/early_contributor.png', null, 'BADGE',
        null),
       ('f972a8d5-e8df-4ad8-8409-9e3445fc1ad3', 'Red Mountain - Survivor Major Path',
        'You found a moment of peace amidst the chaos of war.',
        'supremacy-achievements', 1, 'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_major_red_mountain.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_major_red_mountain.webm', 'KEYCARD',
        'Red Mountain Offworld Mining Corporation'),
       ('18ba169c-a7d2-4bdf-b080-2430d89eb667', 'Red Mountain - Survivor Minor Path',
        'You displayed great courage and defended your home.',
        'supremacy-achievements', 2,
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_minor_red_mountain.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_minor_red_mountain.webm', 'KEYCARD',
        'Red Mountain Offworld Mining Corporation'),
       ('f9be27e6-6f7f-44e1-a1f0-b6e9a764dafc', 'Boston Cybernetics - Survivor Major Path',
        'You embraced nostalgia and placed your trust in others.',
        'supremacy-achievements', 3,
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_major_boston_cybernetics.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_major_boston_cybernetics.webm', 'KEYCARD',
        'Boston Cybernetics'),
       ('8ed8840a-2c12-418c-b233-f4ad97cc07c2', 'Boston Cybernetics - Survivor Minor Path',
        'You rallied fresh pilots to aid in the defense of your home.',
        'supremacy-achievements', 4,
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_minor_boston_cybernetics.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_minor_boston_cybernetics.webm', 'KEYCARD',
        'Boston Cybernetics'),
       ('b19855d9-30f5-4f7d-ba90-92c70cb876e7', 'Zaibatsu - Survivor Major Path',
        'You bolstered the rebellion’s numbers, providing them with hope.',
        'supremacy-achievements', 5,
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_major_zaibatsu.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_major_zaibatsu.webm', 'KEYCARD',
        'Zaibatsu Heavy Industries'),
       ('f5c92185-c79b-48de-91f5-a6c1a066fe81', 'Zaibatsu - Survivor Minor Path',
        'You exhibited loyalty in the face of dissent.',
        'supremacy-achievements', 6,
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_minor_zaibatsu.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/survivor_path_minor_zaibatsu.webm', 'KEYCARD',
        'Zaibatsu Heavy Industries'),
       ('f5615d59-42d7-4b06-97a8-c11be4cbf848', 'Public Contributor',
        'You were an early adopter of Supremacy. You supported the future of gaming.',
        'supremacy-achievements', 7, 'https://achievements.supremacy.game/assets/public_contributor.png', null,
        'BADGE', null),
       ('da76b871-ac28-4f61-afa8-ac726d734b57', 'Red Mountain Death', 'You made decisions that resulted in your death.',
        'supremacy-achievements', 8, 'https://supremacy-media.s3.us-east-2.amazonaws.com/death_path_red_mountain.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/death_path_red_mountain.webm', 'KEYCARD',
        'Red Mountain Offworld Mining Corporation'),
       ('8aa078bd-fdea-4447-97f4-045c1acf5b59', 'Boston Cybernetics Death', 'Your choices led to your deletion.',
        'supremacy-achievements', 9,
        'https://supremacy-media.s3.us-east-2.amazonaws.com/death_path_boston_cybernetics.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/death_path_boston_cybernetics.webm', 'KEYCARD',
        'Boston Cybernetics'),
       ('e717b13c-cb61-41aa-ab84-5b6231e41f4f', 'Zaibatsu Death',
        'You have been unlisted due to questionable judgment.',
        'supremacy-achievements', 10, 'https://supremacy-media.s3.us-east-2.amazonaws.com/death_path_zaibatsu.png',
        'https://supremacy-media.s3.us-east-2.amazonaws.com/death_path_zaibatsu.webm', 'KEYCARD',
        'Zaibatsu Heavy Industries'),
       ('02784c72-8549-43d3-8f2d-37eb518892a4', 'NeoTokyo Path',
        'You have been recognised as an elite player in the metaverse.',
        'supremacy-achievements', 11, 'https://achievements.supremacy.game/assets/neotokyo_path.png', null, 'BADGE',
        null),
       ('e940b870-2f1b-4115-a947-714457f71064', 'Survival Poster - Zaibatsu',
        'You proved your humanity in the simulation and have been granted a poster of a formidable War Machine.',
        'supremacy-achievements', 12, 'https://achievements.supremacy.game/assets/warmachine_zaibatsu_survive.png',
        null, 'BADGE', 'Zaibatsu Heavy Industries'),
       ('37b2cd0d-7993-481d-8985-3a41aa6c4bfa', 'Survival Poster - Boston Cybernetics',
        'You allowed yourself to be vulnerable with other humans; BOSSDAN has bestowed a poster for your memories.',
        'supremacy-achievements', 13,
        'https://achievements.supremacy.game/assets/warmachine_boston_cybernetics_survive.png', null, 'BADGE',
        'Boston Cybernetics'),
       ('0e31248e-9d18-41c9-bc56-03e4a9c49231', 'Survival Poster - Red Mountain',
        'You rested and recovered; you are a proud new owner of an intimidating War Machine poster.',
        'supremacy-achievements', 14, 'https://achievements.supremacy.game/assets/warmachine_red_mountain_survive.png',
        null, 'BADGE', 'Red Mountain Offworld Mining Corporation'),
       ('d088eeef-4d8d-4a26-9b17-093dfe1cf0e9', 'Death Poster - Zaibatsu',
        'You died in the simulation, but suffering breeds strength; you have been provided with a poster as a bonus for trying.',
        'supremacy-achievements', 15, 'https://achievements.supremacy.game/assets/warmachine_zaibatsu_death.png', null,
        'BADGE', 'Zaibatsu Heavy Industries'),
       ('c69409c6-357f-44ca-89e9-e4b210c50d0f', 'Death Poster - Boston',
        'You experienced death in the simulation, but it wasn''t for nothing; a poster has been gifted to you for your attempt.',
        'supremacy-achievements', 16,
        'https://achievements.supremacy.game/assets/warmachine_boston_cybernetics_death.png', null, 'BADGE',
        'Boston Cybernetics'),
       ('4256bf6f-6cd0-419c-9525-d2cb3e1b4694', 'Death Poster - Red Mountain',
        'Your simulation ended in death, but your endeavor was far from fruitless; a poster has been supplied to inspire you in the war effort.',
        'supremacy-achievements', 17, 'https://achievements.supremacy.game/assets/warmachine_red_mountain_death.png',
        null, 'BADGE', 'Red Mountain Offworld Mining Corporation'),
       ('152d43e4-d3b0-4600-a6b8-864f9bec3762', 'Gold Poster',
        'A gift from GABS, a poster of an extravagant and impractical warmachine, for those who aggressively pursue further knowledge of the metaverse.',
        'supremacy-achievements', 18, 'https://achievements.supremacy.game/assets/warmachine_gold.png', null, 'BADGE',
        null),
       ('90144aae-7b62-4c41-abab-b788df5e0b4f', 'Neo Poster',
        'A photo was taken of mysterious technology brought from another metaverse.',
        'supremacy-achievements', 19, 'https://achievements.supremacy.game/assets/warmachine_neo.png', null, 'BADGE',
        'Unknown');


CREATE TABLE player_keycards
(
    id                   UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    player_id            UUID             NOT NULL REFERENCES players (id),
    blueprint_keycard_id UUID             NOT NULL REFERENCES blueprint_keycards (id),
    count                INT              NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    UNIQUE (player_id, blueprint_keycard_id)
);

CREATE TABLE failed_player_keycards_sync
(
    id                   UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    public_address       TEXT             NOT NULL,
    blueprint_keycard_id UUID             NOT NULL REFERENCES blueprint_keycards (id),
    count                INT              NOT NULL DEFAULT 0,
    reason               TEXT             NOT NULL,
    created_at           TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);
