ALTER TYPE MOD_ACTION_TYPE ADD VALUE 'LOOKUP';
ALTER TYPE MOD_ACTION_TYPE ADD VALUE 'MECH_RENAME';
ALTER TYPE MOD_ACTION_TYPE ADD VALUE 'USER_RENAME';

ALTER TABLE mod_action_audit
    ADD COLUMN affected_player_id UUID references players (id) NULL;