ALTER TYPE BOOST_STAT
    ADD VALUE 'MECH_MAX_SHIELD';

ALTER TYPE BOOST_STAT
    ADD VALUE 'MECH_SPRINT_SPREAD_MODIFIER';

ALTER TYPE BOOST_STAT
    ADD VALUE 'MECH_WALK_SPEED_MODIFIER';

ALTER TYPE BOOST_STAT
    ADD VALUE 'WEAPON_DAMAGE_FALLOFF';

ALTER TYPE BOOST_STAT
    ADD VALUE 'WEAPON_SPREAD';

