-- dont drop battle arena
ALTER TABLE battle_arena ALTER COLUMN gid DROP NOT NULL;
ALTER TABLE battle_arena ADD COLUMN IF NOT EXISTS type TEXT;

DROP TYPE IF EXISTS ARENA_TYPE_ENUM;
CREATE TYPE ARENA_TYPE_ENUM AS ENUM ('STORY','EXPEDITION');